### PR TITLE
footer redesign #850

### LINKED ISSUE #850: Footer redesign
**Description**:
As part of the homepage redesign https://github.com/ral-facilities/datagateway/issues/954, modify the footer

- [x] Change footer to look like mockup
- [x] Add contact link to footer with a `mailto:` link

https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/144657834/simulate/no-panels

**Acceptance criteria**:
- [ ] Above changes made

### PR DESCRIPTION
**Pull request by joshuadkitenge**
## Description
As part of the homepage redesign ral-facilities/datagateway#954, modify the footer to match the UX pin design below:

https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/144657834/simulate/no-panels
## Testing instructions
check footer in the various contrast mode to see if they satisfy WCAG 2.1 guidelines (https://github.com/ral-facilities/scigateway/pull/819)

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes #850

### CODE REVIEW

**Comment by joshuadkitenge** [comment]
Screenshot 2021-12-06 155307

**Comment by joshuadkitenge** [comment]
Screenshot 2021-12-06 154724
Screenshot 2021-12-06 154656

**Review by joelvdavies — CHANGES_REQUESTED** [review]
Looks good. I think the position of the footer needs to be changed from `absolute` since it doesn't move like the main app bar when the navigation drawer opens.

image

Also the links on the help page are also changed by this so they are hard to see. I would suggest reverting the link colours and adding a new one just for the footer for now and use the same colour for the visited state as currently its hard to see.

**Comment by joshuadkitenge** [comment]
From the UXpin desgin the footer is absolute. The navigation drawer has been made smaller, so it doesn't interfere with both the main app bar and the footer.

**Review by joelvdavies — APPROVED** [review]
Looks good. CI passes.

**Pull request merged**
