### PR TITLE
Migrate CI builds from Travis to GitHub Actions

### LINKED ISSUE #518: Migrate CI builds from Travis to GitHub Actions
**Description**:
The CI builds needs to be migrated from Travis to GitHub Actions.

**Acceptance criteria**:
- [ ] CI builds run
- [ ] Codecov report posted

### PR DESCRIPTION
**Pull request by VKTB**
## Description
Migrates the Travis CI build to GitHub actions.

The CI build is triggered when a PR is opened and when commits are pushed to the opened PRs.

## Testing instructions
- [x] Review code
- [x] Check CI build runs in GitHub actions
- [x] Check codecov report is posted

## Agile board tracking
closes #518

### CODE REVIEW

**Review by stuartpullinger — APPROVED** [review]
Looks good. 👍

**Review by louise-davies — COMMENTED** [review]
Looks good! The only tiny minor issue I can see is this warning in the logs:

```npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1608653837661-0.552728421673683/node but npm is using /opt/hostedtoolcache/node/14.15.1/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.```

There was a line in the Travis yaml file that fixes this warning so it would be nice to have - but it never actually causes any issues so it's not a massive deal. It also occurs in the datagateway CI as well

**Comment by VKTB** [comment]
@louise-davies I addressed the binary mismatch warning in both, this and datagateway's CI.

**Review by louise-davies — APPROVED** [review]

**Comment by VKTB** [comment]
I documented the steps in the [How to migrate CI build from Travis to GitHub Actions](https://github.com/ral-facilities/scigateway/wiki/How-to-migrate-CI-build-from-Travis-to-GitHub-Actions) wiki page to help with migrations in future.

**Pull request merged**
